apiVersion: v1
kind: Service
metadata:
  name: topologist-web-service
  namespace: topologist
spec:
  selector:
    app: topologist-web
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP