version: 2.1

orbs:
  docker: circleci/docker@3.0.1

jobs:
  ci:
    docker:
      - image: cimg/python:3.12.3
    
    steps:
      - checkout

      - run:
          name: Install Lint & Format Tools
          command: |
            pip install flake8 black
      - run:
          name: Run flake8 (Lint)
          command: flake8 .
      - run:
          name: Check code format with black
          command: black --check .

      - setup_remote_docker:
          version: 20.10.24

      - docker/check

      - docker/build:
          image: nonsanxx/topologist-worker
          path: ./worker
          tag: latest
      - docker/push:
          image: nonsanxx/topologist-worker
          tag: latest

      - docker/build:
          image: nonsanxx/topologist-scheduler
          path: ./scheduler
          tag: latest
      - docker/push:
          image: nonsanxx/topologist-scheduler
          tag: latest
      
      - docker/build:
          image: nonsanxx/topologist-web
          path: ./web
          tag: latest
      - docker/push:
          image: nonsanxx/topologist-web
          tag: latest

workflows:
  build_and_push:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main